# docker-compose.yaml

services:
  discord-scanner-bot:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: discord-scanner-bot # Optional: specify a container name
    env_file:
      - .env # Load environment variables from the .env file
    restart: unless-stopped # Automatically restart the container unless manually stopped
    networks:
      - llmnet
networks:
  llmnet:
    external: true
